# Generated by Django 3.2.12 on 2022-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
